name: Samsung EHS MQTT
version: "1.0.4"
slug: samsung_ehs_mqtt
description: Samsung EHS F1/F2 MQTT sensor bridge
url: "https://github.com/dannyverschoore/home-assistant-samsung-ehs-mqtt"

arch:
  - amd64
  - aarch64
  - armv7

startup: application
boot: auto
init: false

build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest

options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  serial_port: "/dev/ttyUSB0"

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str?
  mqtt_password: password?
  serial_port: str

uart: true
